### ISSUE TITLE
How to config checkQuorum to false for raft-rs?

### ISSUE THREAD

**Issue by KunPengRen** [rmqtt/rmqtt-raft#1]
Problem: the leader node will be stuck and constantly compete to become to the leader when it can not receive the Quorum from followers in time.(my follower nodes face a high requests rate from clients). 
Logs:
Sep 06 10:51:16.588 WARN stepped down to follower since quorum is not active, raft_id: 1, version: 1.0.0
Sep 06 10:51:16.588 INFO became follower at term 2, term: 2, raft_id: 1, version: 1.0.0
Sep 06 10:51:18.407 INFO starting a new election, term: 2, raft_id: 1, version: 1.0.0
Sep 06 10:51:18.407 INFO became pre-candidate at term 2, term: 2, raft_id: 1, version: 1.0.0
Sep 06 10:51:18.407 INFO broadcasting vote request, to: [2, 3], log_index: 6, log_term: 2, term: 2, type: MsgRequestPreVote, raft_id: 1, version: 1.0.0
Sep 06 10:51:20.227 INFO starting a new election, term: 2, raft_id: 1, version: 1.0.0
Sep 06 10:51:20.227 INFO became pre-candidate at term 2, term: 2, raft_id: 1, version: 1.0.0
Sep 06 10:51:20.227 INFO broadcasting vote request, to: [2, 3], log_index: 6, log_term: 2, term: 2, type: MsgRequestPreVote, raft_id: 1, version: 1.0.0
Sep 06 10:51:22.047 INFO starting a new election, term: 2, raft_id: 1, version: 1.0.0
Sep 06 10:51:22.047 INFO became pre-candidate at term 2, term: 2, raft_id: 1, version: 1.0.0
Sep 06 10:51:22.047 INFO broadcasting vote request, to: [2, 3], log_index: 6, log_term: 2, term: 2, type: MsgRequestPreVote, raft_id: 1, version: 1.0.0
Sep 06 10:51:23.865 INFO starting a new election, term: 2, raft_id: 1, version: 1.0.0
Sep 06 10:51:23.865 INFO became pre-candidate at term 2, term: 2, raft_id: 1, version: 1.0.0
Sep 06 10:51:23.865 INFO broadcasting vote request, to: [2, 3], log_index: 6, log_term: 2, term: 2, type: MsgRequestPreVote, raft_id: 1, version: 1.0.0

Reason:
I check the reason is checkQuorum is set as true. So do the maintainer know how to set checkQuorum to false when starting the RAFT nodes?

**Comment by tryor** [comment]
See raft_node.rs#new_config(..)
    #[inline]
    fn new_config(id: u64, election_tick: usize, heartbeat_tick: usize) -> Config {
        Config {
            id,
            election_tick,
            heartbeat_tick,
            **check_quorum: true,**
            pre_vote: true,
            ..Default::default()
        }
    }
